export const FETCH_PENDING = "FETCH_PENDING";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
export const FETCH_MORE = "FETCH_MORE";
export const RESET_LIMIT = "RESET_LIMIT";

export const FETCH_DETAIL_PENDING = "FETCH_DETAIL_PENDING";
export const FETCH_DETAIL_SUCCESS = "FETCH_DETAIL_SUCCESS";
export const FETCH_DETAIL_ERROR = "FETCH_DETAIL_ERROR";

export const INPUT_CHANGE = "INPUT_CHANGE";
export const RESET_INPUT = "RESET_INPUT";